using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using StaticFiles.IncrementalGenerator.Tests;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using Xunit;

namespace Advanced.IncrementalGenerator.Tests
{
    public class ConstStringsFromFilesGeneratorTests
    {
        public class AdditionalTextTestFile : AdditionalText
        {
            private string _fileId;

            public override string Path => $"path/{_fileId}.txt";

            public override SourceText GetText(CancellationToken cancellationToken = default)
            {
                return SourceText.From("This is a text file");
            }

            public AdditionalTextTestFile(string fileId)
            {
                _fileId = fileId;
            }
        }

        [Fact]
        public void Generate_2_Files_Success()
        {
            // Input to use as a source for generation
            var inputSourceCode =
@"
using Advanced.IncrementalGenerator;

namespace Advanced.IncrementalGenerator.Tests
{
    // Partial class for generating const strings
    public static partial class ConstStringsFromIncrementalGenerator
    {

    }
}
";
            var additionalTexts = new List<AdditionalText>
            {
                new AdditionalTextTestFile("file1"),
                new AdditionalTextTestFile("file2")
            };


            // Actual result generated by the Source Generator based on input
            var expectedGeneratedCode =
@"// <auto-generated/>
using System;

namespace Advanced.IncrementalGenerator.Tests
{
    public static partial class Program
    {
        static partial void HelloFromIncrementalGenerator(string name) =>
            Console.WriteLine($""Generator says: Hi from '{name}'"");
    }
}
";

            var result = CSharpIncrementalGeneratorVerifier<ConstStringsFromFilesGenerator>.Verify(inputSourceCode, new ConstStringsFromFilesGenerator(), additionalTexts);

            Assert.True(result.Diagnostics.IsEmpty);
            Assert.Single(result.Results);

            var resultRun = result.Results[0];
            Assert.Equal(2, resultRun.GeneratedSources.Length);

            Assert.Equal(expectedGeneratedCode, resultRun.GeneratedSources[0].SourceText.ToString());
            Assert.Equal("ConstStringsFromIncrementalGenerator.g.cs", resultRun.GeneratedSources[0].HintName);
        }
    }
}
