using StaticFiles.IncrementalGenerator.Tests;
using Xunit;

namespace Advanced.IncrementalGenerator.Tests
{
    public class HelloSourceIncrementalGeneratorTests
    {
        [Fact]
        public void Generate_1_Method_Success()
        {
            // Input to use as a source for generation
            var inputSourceCode =
@"
using Advanced.IncrementalGenerator;

namespace Advanced.IncrementalGenerator.Tests
{
    partial class Program
    {
        static void Main(string[] args)
        {
            HelloFromIncrementalGenerator(""SourceGenerator !"");
        }

        // This will be generated:
        [GenerateHelloSourceIncremental]
        static partial void HelloFromIncrementalGenerator(string name);
    }
}
";
            // Actual result generated by the Source Generator based on input
            var expectedGeneratedCode =
@"// <auto-generated/>
using System;

namespace Advanced.IncrementalGenerator.Tests
{
    public static partial class Program
    {
        static partial void HelloFromIncrementalGenerator(string name) =>
            Console.WriteLine($""Generator says: Hi from '{name}'"");
    }
}
";

            var result = CSharpIncrementalGeneratorVerifier<HelloSourceIncrementalGenerator>.Verify(inputSourceCode, new HelloSourceIncrementalGenerator());

            Assert.True(result.Diagnostics.IsEmpty);
            Assert.Single(result.Results);

            var resultRun = result.Results[0];
            Assert.Single(resultRun.GeneratedSources);

            Assert.Equal(expectedGeneratedCode, resultRun.GeneratedSources[0].SourceText.ToString());
            Assert.Equal("Program.g.cs", resultRun.GeneratedSources[0].HintName);
        }


        [Fact]
        public void Generate_0_Method_Success()
        {
            // Input to use as a source for generation
            var inputSourceCode =
@"
using Advanced.IncrementalGenerator;

namespace Advanced.IncrementalGenerator.Tests
{
    partial class Program
    {
        static void Main(string[] args)
        {
            HelloFromIncrementalGenerator(""SourceGenerator !"");
        }

        // This doesn't have generator, won't be generated
        static partial void HelloFromIncrementalGenerator(string name);
    }
}
";
            var result = CSharpIncrementalGeneratorVerifier<HelloSourceIncrementalGenerator>.Verify(inputSourceCode, new HelloSourceIncrementalGenerator());

            Assert.True(result.Diagnostics.IsEmpty);
            Assert.Single(result.Results);

            var resultRun = result.Results[0];
            Assert.Empty(resultRun.GeneratedSources); // 1 - No files should be generated
        }
    }
}
